### PR TITLE
Use en.error from master error file

### PR DESCRIPTION
**Pull request by lcai006**
Extract en.error from umple.jar
Rewrite en.error file when umple is updated for a new release.

### CODE REVIEW

**Comment by lcai006** [comment]
@Digized 
I have made changes for the extension, are you able to create a release, or any instruction for an auto release?

**Comment by Digized** [comment]
hey @lcai006 got it. I will try to get out a release tonight. Ive not had much time to automate the release for this project, unfortunately its a pretty manual process.

**Comment by TimLethbridge** [comment]
@digized thanks! If there is a way you could give instructions so future students (or me) could do the (most of or all of the) manual steps easily, then we wouldn't need to rely on you so much.

**Comment by Digized** [comment]
unfortunately they are tied to my credentials, I'll try to see if I can create a system using gh actions to setup continuous deployment on this    sometime this week/next week. it's AWS re:invent so we have been trying to get new features out for our service.

**Comment by Digized** [comment]
this has been released now. the procedure to publish is here: https://github.com/umple/Umple-for-Vscode/wiki/Releasing-a-new-version

**Pull request merged**
